name: Result test lessons

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B install

      # Проверка урока 1 с одним выводом
      - name: Урок 1 - Результат
        run: |
          if mvn -Dtest=lessons.lesson1.MainTest test | grep -q 'BUILD SUCCESS'; then
            echo "Урок 1 пройден"
          else
            echo "Урок 1 не пройден"
          fi

      # Проверка урока 2 с одним выводом
      - name: Урок 2 - Результат
        run: |
          if mvn -Dtest=lessons.lesson2.MainTest test | grep -q 'BUILD SUCCESS'; then
            echo "Урок 2 пройден"
          else
            echo "Урок 2 не пройден"
          fi
