name: Java CI

on:
  push:
    branches:
      - master  # Укажите ветку, на которую нужно реагировать, например, master
  pull_request:
    branches:
      - master  # Укажите ветку, на которую нужно реагировать, например, master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B install

      - name: Run tests
        run: mvn test
