name: Result test lessons

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B install

      # Проверка урока 1
      - name: Run tests for Lesson 1
        id: lesson1
        continue-on-error: true
        run: |
          echo "Запуск тестов для Урока 1"
          mvn -Dtest=lessons.lesson1.MainTest test

      - name: Урок 1 - Результат
        if: ${{ steps.lesson1.outcome == 'success' }}
        run: echo "Урок 1 пройден"
      - name: Урок 1 - Результат (Не пройден)
        if: ${{ steps.lesson1.outcome == 'failure' }}
        run: echo "Урок 1 не пройден"

      # Проверка урока 2
      - name: Run tests for Lesson 2
        id: lesson2
        continue-on-error: true
        run: |
          echo "Запуск тестов для Урока 2"
          mvn -Dtest=lessons.lesson2.MainTest test

      - name: Урок 2 - Результат
        if: ${{ steps.lesson2.outcome == 'success' }}
        run: echo "Урок 2 пройден"
      - name: Урок 2 - Результат (Не пройден)
        if: ${{ steps.lesson2.outcome == 'failure' }}
        run: echo "Урок 2 не пройден"
