name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B install

      # Проверка урока 1
      - name: Run tests for Lesson 1
        run: mvn -Dtest=lessons.lesson1.MainTest test
        continue-on-error: true
        if: success()
        display-name: "Lesson 1 Tests"
        env:
          LESSON_NAME: "Lesson 1"
      - name: Check Lesson 1 Result
        if: failure()
        run: echo "$LESSON_NAME not passed" || echo "$LESSON_NAME passed"

      # Проверка урока 2
      - name: Run tests for Lesson 2
        run: mvn -Dtest=lessons.lesson2.MainTest test
        continue-on-error: true
        if: success()
        display-name: "Lesson 2 Tests"
