name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B install

      # Проверка урока 1
      - name: Run tests for Lesson 1
        run: |
          echo "Starting tests for Lesson 1"
          mvn -Dtest=lessons.lesson1.MainTest test
        continue-on-error: true

      - name: Check Lesson 1 Result
        if: failure()
        run: echo "Lesson 1 tests failed"
        if: success()
        run: echo "Lesson 1 tests passed"

      # Проверка урока 2
      - name: Run tests for Lesson 2
        run: |
          echo "Starting tests for Lesson 2"
          mvn -Dtest=lessons.lesson2.MainTest test
        continue-on-error: true

      - name: Check Lesson 2 Result
        if: failure()
        run: echo "Lesson 2 tests failed"
        if: success()
        run: echo "Lesson 2 tests passed"
